{
 "title": "Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "LOKI_DS", "query": "loki" },
   { "name": "job", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "description": "blabla",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{job=\"$job\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Go version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{job=\"${job}\"}",
     "legendFormat": "{{ goversion }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "content": "<img \nwidth=\"100%\"\nheight=\"100%\"\nsrc=\"https://public.amsdard.io/kapitan_bomba/003.jpg\">\n</img>"
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"${job}\"}"
    }
   ]
  },
  {
   "title": "Scrapes / minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count{job=\"$job\"}[$__rate_interval]) * 60",
     "legendFormat": "scrapes/min"
    }
   ]
  },
  {
   "title": "Time series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"$job\"}",
     "legendFormat": "time series"
    }
   ]
  },
  {
   "title": "Samples appended / s",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "appends/s"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "description": "Number of configured uniq jobs.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(prometheus_sd_discovered_targets{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Retention",
   "type": "stat",
   "description": "blabla...",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prometheus_tsdb_lowest_timestamp_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "description": "In K8S this value is actually number of discovered targets, not scraped, so the value is bullshit.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "TSDB",
   "type": "row",
   "gridPos": { "X": 0, "h": 1, "w": 24, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_storage_blocks_bytes{job=\"$job\"}",
       "legendFormat": "storage size"
      }
     ]
    },
    {
     "title": "Samples appended / s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "appends/s"
      }
     ]
    },
    {
     "title": "Blocks loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "prometheus_tsdb_blocks_loaded{job=\"$job\"}",
       "legendFormat": "blocks"
      }
     ]
    },
    {
     "title": "Series (head block)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_series_created_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "series created"
      },
      {
       "expr": "increase(prometheus_tsdb_head_series_removed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "series removed"
      },
      {
       "expr": "prometheus_tsdb_head_series{job=\"$job\"}",
       "legendFormat": "series total"
      }
     ]
    },
    {
     "title": "Chunks (head block)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_chunks_created_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "chunks created"
      },
      {
       "expr": "increase(prometheus_tsdb_head_chunks_removed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "chunks removed"
      },
      {
       "expr": "prometheus_tsdb_head_chunks{job=\"$job\"}",
       "legendFormat": "chunks total"
      }
     ]
    },
    {
     "title": "GC duration (head block) (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{job=\"$job\"}[$__rate_interval]) /\nrate(prometheus_tsdb_head_gc_duration_seconds_count{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "gc duration"
      }
     ]
    },
    {
     "title": "Compaction duration (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{job=\"$job\"}[$__rate_interval]) /\nrate(prometheus_tsdb_compaction_duration_seconds_count{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "compaction duration"
      }
     ]
    },
    {
     "title": "WAL fsync duration (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{job=\"$job\"}[$__rate_interval]) /\nrate(prometheus_tsdb_wal_fsync_duration_seconds_count{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "fsync duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Scraping",
   "type": "row",
   "gridPos": { "X": 0, "h": 1, "w": 24, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrapes / minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_count{job=\"$job\"}[$__rate_interval]) * 60",
       "legendFormat": "scrapes/min"
      }
     ]
    },
    {
     "title": "Scrape intervals",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_target_interval_length_seconds{job=\"$job\", quantile=\"0.9\"}",
       "legendFormat": "q0.9 ({{ interval }} int)"
      },
      {
       "expr": "prometheus_target_interval_length_seconds{job=\"$job\", quantile=\"0.99\"}",
       "legendFormat": "q0.99 ({{ interval }} int)"
      }
     ]
    },
    {
     "title": "Most samples top5",
     "type": "table",
     "description": "Which job produces the biggest number of samples.\n\nIf a job has multiple instances, only one is displayed, the one with biggest number (by using `max by (job)`.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "topk(5,\n  max by (job) (scrape_samples_scraped)\n)"
      }
     ]
    },
    {
     "title": "Longest scrapes top5",
     "type": "table",
     "description": "Which job took the longest.\n\nThe value is calculated as average of all the values from the last 1h (by using `avg_over_time[1h]`)\n\nIf a job has multiple instances, only one is displayed, the one with longest scrape (by using `max by (job)`.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5,\n  max by (job) (avg_over_time(scrape_duration_seconds[1h]))\n)"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "content": "# good to know\n- metric = a single \"word\" without any labels (dimension) attached to it\n- series = metric + uniq labels (hence, a single metric can have hundred of series)\n- sample = series + timestamp + value\n\n# handy queries\n- top 10 metrics with the biggest number of series\n    ```\n    topk(10, count by (__name__) ({__name__=~\".+\"}))\n    ```\n- top 10 jobs with the biggest number of series\n    ```\n    topk(10, sum by (job) (scrape_samples_scraped))\n    ```"
    }
   ]
  },
  {
   "title": "Query engine and HTTP",
   "type": "row",
   "gridPos": { "X": 0, "h": 1, "w": 24, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Engine query: queries / s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_count{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ slice }}"
      }
     ]
    },
    {
     "title": "Engine query: queries duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "# avg = sum / count\n\nrate(prometheus_engine_query_duration_seconds_sum{job=\"$job\"}[$__rate_interval]) /\nrate(prometheus_engine_query_duration_seconds_count{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ slice }} (avg)"
      },
      {
       "expr": "prometheus_engine_query_duration_seconds{job=\"$job\", quantile=\"0.9\"}",
       "legendFormat": "{{ slice }} (q0.9)"
      }
     ]
    },
    {
     "title": "Engine query: active queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "prometheus_engine_queries{job=\"$job\"}",
       "legendFormat": "active queries"
      },
      {
       "expr": "prometheus_engine_queries_concurrent_max{job=\"$job\"}",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Http: requests / s",
     "type": "timeseries",
     "description": "Edit or explore this panel to see requests rate per handler.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum (rate(prometheus_http_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum (rate(prometheus_http_request_duration_seconds_count{job=\"$job\", handler!=\"/metrics\"}[$__rate_interval]))",
       "legendFormat": "total (w/o /metrics)"
      },
      {
       "expr": "rate(prometheus_http_request_duration_seconds_count{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "Http: requests duration (avg)",
     "type": "timeseries",
     "description": "Edit or explore this panel to see requests rate per handler.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (rate(prometheus_http_request_duration_seconds_sum{job=\"$job\"}[$__rate_interval])) /\nsum (rate(prometheus_http_request_duration_seconds_count{job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum (rate(prometheus_http_request_duration_seconds_sum{job=\"$job\", handler!=\"/metrics\"}[$__rate_interval])) /\nsum (rate(prometheus_http_request_duration_seconds_count{job=\"$job\", handler!=\"/metrics\"}[$__rate_interval]))",
       "legendFormat": "total (w/o /metrics)"
      },
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"$job\"}[$__rate_interval]) /\nrate(prometheus_http_request_duration_seconds_count{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "Http: response size (avg)",
     "type": "timeseries",
     "description": "Edit or explore this panel to see requests rate per handler.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_http_response_size_bytes_sum{job=\"$job\"}[$__rate_interval])) / \nsum(rate(prometheus_http_response_size_bytes_count{job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(rate(prometheus_http_response_size_bytes_sum{job=\"$job\", handler!=\"/metrics\"}[$__rate_interval])) / \nsum(rate(prometheus_http_response_size_bytes_count{job=\"$job\", handler!=\"/metrics\"}[$__rate_interval]))",
       "legendFormat": "total (w/o /metrics)"
      },
      {
       "expr": "rate(prometheus_http_response_size_bytes_sum{job=\"$job\"}[$__rate_interval]) / \nrate(prometheus_http_response_size_bytes_count{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ handler }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "X": 0, "h": 1, "w": 24, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http failed requests",
     "type": "timeseries",
     "description": "Requests that returned 4** or 5**.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(\n  increase(prometheus_http_requests_total{job=\"$job\", code!~\"2..|3..\"}[$__rate_interval])\n)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Dialer connection errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "targets": [
      {
       "expr": "sum by (dialer_name) (increase(net_conntrack_dialer_conn_failed_total{job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{ dialer_name }}"
      }
     ]
    },
    {
     "title": "Scrape errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "targets": [
      {
       "expr": "increase(prometheus_target_scrapes_exceeded_body_size_limit_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "exceeded_body_size_limit"
      },
      {
       "expr": "increase(prometheus_target_scrapes_exceeded_sample_limit_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "exceeded_sample_limit"
      },
      {
       "expr": "increase(prometheus_target_scrapes_exemplar_out_of_order_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "exemplar_out_of_order"
      },
      {
       "expr": "increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "sample_duplicate_timestamp"
      },
      {
       "expr": "increase(prometheus_target_scrapes_sample_out_of_bounds_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "sample_out_of_bounds"
      },
      {
       "expr": "increase(prometheus_target_scrapes_sample_out_of_order_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "sample_out_of_order"
      }
     ]
    },
    {
     "title": "Scrape pools errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "increase(prometheus_target_scrape_pool_exceeded_label_limits_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "exceeded_label_limits"
      },
      {
       "expr": "increase(prometheus_target_scrape_pool_exceeded_target_limit_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "exceeded_target_limit"
      },
      {
       "expr": "increase(prometheus_target_scrape_pool_reloads_failed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "reloads_failed"
      },
      {
       "expr": "increase(prometheus_target_scrape_pools_failed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "creation_failed"
      }
     ]
    },
    {
     "title": "Service discovery errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "increase(prometheus_sd_dns_lookup_failures_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "dns_lookup_failures"
      },
      {
       "expr": "sum(prometheus_sd_failed_configs{job=\"$job\"})",
       "legendFormat": "failed_configs"
      },
      {
       "expr": "increase(prometheus_sd_file_read_errors_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "file_read_errors"
      }
     ]
    },
    {
     "title": "TSDB errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_series_not_found_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "series_not_found"
      },
      {
       "expr": "increase(prometheus_tsdb_out_of_bound_samples_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "out_of_bound_samples"
      },
      {
       "expr": "increase(prometheus_tsdb_compactions_failed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "compactions_failed"
      },
      {
       "expr": "increase(prometheus_tsdb_head_truncations_failed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "head_truncations_failed"
      },
      {
       "expr": "increase(prometheus_tsdb_checkpoint_creations_failed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "checkpoint_creations_failed"
      },
      {
       "expr": "increase(prometheus_tsdb_checkpoint_deletions_failed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "checkpoint_deletions_failed"
      },
      {
       "expr": "increase(prometheus_tsdb_mmap_chunk_corruptions_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "mmap_chunk_corruptions"
      },
      {
       "expr": "increase(prometheus_tsdb_reloads_failures_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "reloads_failures"
      },
      {
       "expr": "increase(prometheus_tsdb_wal_corruptions_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "wal_corruptions"
      },
      {
       "expr": "increase(prometheus_tsdb_wal_truncations_failed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "wal_truncations_failed"
      },
      {
       "expr": "increase(prometheus_tsdb_wal_writes_failed_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "wal_writes_failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus internals (process and self scrape info)",
   "type": "row",
   "gridPos": { "X": 0, "h": 1, "w": 24, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "cpu usage"
      }
     ]
    },
    {
     "title": "Goroutines and threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\"}",
       "legendFormat": "goroutines"
      },
      {
       "expr": "go_threads{job=\"$job\"}",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\"}",
       "legendFormat": "open files"
      },
      {
       "expr": "process_max_fds{job=\"$job\"}",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\"}",
       "legendFormat": "resident memory"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "allocations"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}",
       "legendFormat": "inuse"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "go_memstats_heap_objects{job=\"$job\"}",
       "legendFormat": "objects"
      }
     ]
    },
    {
     "title": "Garbage collection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_count{job=\"$job\"}[$__rate_interval]) * 60",
       "legendFormat": "GCs / minute"
      },
      {
       "expr": "# avg = sum / caount\nrate(go_gc_duration_seconds_sum{job=\"$job\"}[$__rate_interval]) /\nrate(go_gc_duration_seconds_count{job=\"$job\"}[$__rate_interval])",
       "legendFormat": "GC time (avg)"
      },
      {
       "expr": "go_gc_duration_seconds{job=\"$job\", quantile=\"0.75\"}",
       "legendFormat": "GC time (q=0.75)"
      },
      {
       "expr": "go_gc_duration_seconds{job=\"$job\", quantile=\"1\"}",
       "legendFormat": "GC time (q=1)"
      }
     ]
    },
    {
     "title": "Self scraping: samples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "scrape_samples_scraped{job=\"$job\"}",
       "legendFormat": "samples scraped"
      },
      {
       "expr": "scrape_series_added{job=\"$job\"}",
       "legendFormat": "series added"
      }
     ]
    },
    {
     "title": "Self scraping: duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "scrape_duration_seconds{job=\"$job\"}",
       "legendFormat": "scrape duration"
      }
     ]
    },
    {
     "title": "Self scraping: http responses / minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "targets": [
      {
       "expr": "rate(promhttp_metric_handler_requests_total{job=\"$job\"}[$__rate_interval]) * 60",
       "legendFormat": "{{ code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus logs",
   "type": "row",
   "gridPos": { "X": 0, "h": 1, "w": 24, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{app=\"${job}\"}"
      }
     ]
    }
   ]
  }
 ]
}